---
title: Local Objects
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@local-objects.com
description: Local Objects [LO] is a journal featuring ordinary objects made and used
  in Korea.  LO focuses on objects’ local identity in Korean society through stories
  of usage, language, history, aesthetics and materiality.
baseurl: ''
url: ''
twitter_username: placeholder
github_username: ecohen-wmde
theme: minima
plugins:
- jekyll-feed
